name: Reusable Infra CI

on:
  workflow_call:

jobs:
  validate-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f infra/docker-compose.yml config
        continue-on-error: true

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      - run: terraform fmt -check
        working-directory: infra/terraform
        continue-on-error: true
      - run: terraform init
        working-directory: infra/terraform
      - run: terraform validate
        working-directory: infra/terraform
